# Generated by Django 4.2.7 on 2023-11-18 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment_slug'),
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeWatchPlanned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_animes', models.ManyToManyField(related_name='planned_animes', to='catalog.anime', verbose_name='Запланированные аниме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('watched_animes', models.ManyToManyField(related_name='watched_animes', to='catalog.anime', verbose_name='Просмотренные аниме')),
            ],
        ),
    ]
