# Generated by Django 4.2.7 on 2023-11-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment_slug'),
        ('users', '0003_useranimewatchplanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranimewatchplanned',
            name='planned_animes',
        ),
        migrations.RemoveField(
            model_name='useranimewatchplanned',
            name='watched_animes',
        ),
        migrations.AddField(
            model_name='useranimewatchplanned',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.anime', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='useranimewatchplanned',
            name='status',
            field=models.CharField(choices=[('wa', 'Просмотрено'), ('zp', 'Запланирован')], default='zp', max_length=2, verbose_name='Статус аниме'),
        ),
    ]
