# Generated by Django 4.2.7 on 2023-11-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment_slug'),
        ('users', '0004_remove_useranimewatchplanned_planned_animes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranimewatchplanned',
            options={'verbose_name': 'Список аниме пользователя', 'verbose_name_plural': 'Списки аниме пользователя'},
        ),
        migrations.AlterField(
            model_name='useranimewatchplanned',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='useranimewatchplanned',
            name='status',
            field=models.CharField(choices=[('wa', 'Просмотрено'), ('zp', 'Запланирован')], max_length=2, verbose_name='Статус аниме'),
        ),
    ]
