# Generated by Django 4.2.7 on 2023-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useranimewatchplanned_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimewatchplanned',
            name='status',
            field=models.CharField(choices=[('wa', 'Просмотрено'), ('zp', 'Запланировано')], max_length=2, verbose_name='Статус аниме'),
        ),
    ]
