# Generated by Django 4.2.7 on 2023-11-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='author',
            field=models.CharField(blank=True, help_text='Поле для аниме-фильмов', max_length=200, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='anime',
            name='duration',
            field=models.CharField(blank=True, help_text='Поле для аниме-фильмов', max_length=200, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Студия'),
        ),
    ]
