# Generated by Django 4.2.7 on 2023-11-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(db_index=True, to='catalog.genre', verbose_name='Жанры аниме'),
        ),
    ]
